GET http://localhost:3000/

###

POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
    "email":"birjuchaca@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5000/page/add HTTP/1.1
Content-Type: application/json

{
    "snippet":"bow lo bowser",
    "authorId":"bowser"
}

###
DELETE  http://localhost:5000/page/delete/5fcf93d78cb87f273074c4df HTTP/1.1

###
PUT  http://localhost:5000/page/update/5fcf93d78cb87f273074c4df HTTP/1.1
Content-Type: application/json

{
    "snippet":"bow no bowser",
    "authorId":"bowser"
}

###
GET http://localhost:5000/logout

###
GET http://localhost:5000/page/all